// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_generated

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	JtiHash   string
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	TokenVersion int32
}
