// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package sqlc_generated

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (jti_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	JtiHash   string
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.JtiHash, arg.UserID, arg.ExpiresAt)
	return err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT jti_hash, user_id, expires_at, revoked_at, created_at
FROM sessions
WHERE jti_hash = $1
LIMIT 1
`

func (q *Queries) GetSessionByHash(ctx context.Context, jtiHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, jtiHash)
	var i Session
	err := row.Scan(
		&i.JtiHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = now()
WHERE jti_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, jtiHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, jtiHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsByUser = `-- name: RevokeSessionsByUser :execrows
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
