version: "3.9"

secrets:
  db_password:
    file: ./secrets/db_password.txt

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: appdb
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports: ["5432:5432"]

  migrator:
    image: migrate/migrate:latest
    depends_on:
      db:
        condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "postgres://app:qwe@db:5432/appdb?sslmode=disable",
      "up"
    ]
    volumes:
      - ./internal/infra/db/migrations:/migrations:ro
    restart: "on-failure"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      HTTP_ADDR: :8080
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: app
      DB_NAME: appdb
      SSLMODE: disable
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports: ["8080:8080"]
