version: "3.9"

secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt

services:
  db:
    image: postgres:16-alpine
    secrets:
      - db_password
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
    # expose:
    #   - "${DB_PORT}"
    ports: ["${DB_PORT}:${DB_PORT}"]

  migrator:
    image: migrate/migrate:latest
    depends_on:
      db:
        condition: service_healthy
    command: [
      "-path", "/migrations",
      # все еще светятся секреты
      "-database", "postgres://app:qwe@db:5432/appdb?sslmode=disable",
      "up"
    ]
    # entrypoint: ["/bin/sh", "-lc"]
    # command: |
    #   set -euo pipefail
    #   PASS="$(tr -d '\r\n' < /run/secrets/db_password)"
    #   echo "Running migrations…"
    #   exec /migrate -verbose \
    #     -path /migrations \
    #     -database "postgres://${DB_USER}:$PASS@db:${DB_PORT}/${DB_NAME}?sslmode=disable" \
    #     up
    volumes:
      - ./internal/infra/db/migrations:/migrations:ro
    # secrets:
    #   - db_password
    restart: "on-failure"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env.dev
    depends_on:
      migrator:
        condition: service_completed_successfully
    secrets:
      - db_password
      - jwt_secret
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    expose:
      - ${HTTP_PORT}
    # ports: ["8080:8080"]
    
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_gateway
    depends_on:
      - app
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./static:/var/www/static:ro     # если есть статика
    ports:
      - "80:80"        # наружу торчит только Nginx
    # networks можно оставить по умолчанию (default)