// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client.sql

package sqlc_generated

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createClient = `-- name: CreateClient :exec
INSERT INTO public.client (id,client_name, client_surname, birthday, gender, address_id)
VALUES (
    $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
`

type CreateClientParams struct {
	ID            uuid.UUID
	ClientName    string
	ClientSurname string
	Birthday      time.Time
	Gender        string
	AddressID     uuid.UUID
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) error {
	_, err := q.db.Exec(ctx, createClient,
		arg.ID,
		arg.ClientName,
		arg.ClientSurname,
		arg.Birthday,
		arg.Gender,
		arg.AddressID,
	)
	return err
}

const deleteClient = `-- name: DeleteClient :execrows
DELETE FROM public.client
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateClient = `-- name: UpdateClient :execrows
UPDATE public.client
SET client_name   = $2,
    client_surname= $3,
    birthday      = $4,
    gender        = $5,
    address_id    = $6
WHERE id = $1
`

type UpdateClientParams struct {
	ID            uuid.UUID
	ClientName    string
	ClientSurname string
	Birthday      time.Time
	Gender        string
	AddressID     uuid.UUID
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateClient,
		arg.ID,
		arg.ClientName,
		arg.ClientSurname,
		arg.Birthday,
		arg.Gender,
		arg.AddressID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
