// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: address.sql

package sqlc_generated

import (
	"context"

	uuid "github.com/google/uuid"
)

const createAddress = `-- name: CreateAddress :exec
INSERT INTO address (id, country,city,street)
VALUES ($1, $2, $3, $4)
`

type CreateAddressParams struct {
	ID      uuid.UUID
	Country string
	City    string
	Street  string
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) error {
	_, err := q.db.Exec(ctx, createAddress,
		arg.ID,
		arg.Country,
		arg.City,
		arg.Street,
	)
	return err
}

const deleteAddress = `-- name: DeleteAddress :execrows
DELETE FROM public.address
WHERE id = $1
`

func (q *Queries) DeleteAddress(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAddress, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAddress = `-- name: UpdateAddress :execrows
UPDATE public.address
SET country = $2,
    city    = $3,
    street  = $4
WHERE id = $1
`

type UpdateAddressParams struct {
	ID      uuid.UUID
	Country string
	City    string
	Street  string
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAddress,
		arg.ID,
		arg.Country,
		arg.City,
		arg.Street,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
