// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: address.sql

package sqlc_generated

import (
	"context"

	uuid "github.com/google/uuid"
)

const addAddress = `-- name: AddAddress :exec
INSERT INTO address (id, country,city,street)
VALUES ($1, $2, $3, $4)
`

type AddAddressParams struct {
	ID      uuid.UUID
	Country interface{}
	City    interface{}
	Street  interface{}
}

// -- name: CreateUser :one
// INSERT INTO client (id, client_name,client_surname,birthday,gender,address_id)
// VALUES ($1, $2, $3, $4, $5, $6)
// RETURNING registration_date;
func (q *Queries) AddAddress(ctx context.Context, arg AddAddressParams) error {
	_, err := q.db.Exec(ctx, addAddress,
		arg.ID,
		arg.Country,
		arg.City,
		arg.Street,
	)
	return err
}
