// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client.sql

package sqlc_generated

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :exec
INSERT INTO public.client (id,client_name, client_surname, birthday, gender, address_id)
VALUES (
  $1,
  $2,                     -- client_name
  $3,                     -- client_surname
  $4,                     -- birthday (date, CHECK birthday <= CURRENT_DATE)
  COALESCE($5, 'unknown')::public.gender_t,  -- gender (nullable param -> default 'unknown')
  $6                      -- address_id (nullable)
)
`

type CreateClientParams struct {
	ID            uuid.UUID
	ClientName    interface{}
	ClientSurname interface{}
	Birthday      time.Time
	Column5       GenderT
	AddressID     pgtype.UUID
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) error {
	_, err := q.db.Exec(ctx, createClient,
		arg.ID,
		arg.ClientName,
		arg.ClientSurname,
		arg.Birthday,
		arg.Column5,
		arg.AddressID,
	)
	return err
}

const deleteClient = `-- name: DeleteClient :execrows
DELETE FROM public.client
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateClient = `-- name: UpdateClient :execrows
UPDATE public.client
SET client_name   = $2,
    client_surname= $3,
    birthday      = $4,
    gender        = COALESCE($5, gender), -- если не хочешь менять, передай NULL
    address_id    = $6
WHERE id = $1
`

type UpdateClientParams struct {
	ID            uuid.UUID
	ClientName    interface{}
	ClientSurname interface{}
	Birthday      time.Time
	Gender        GenderT
	AddressID     pgtype.UUID
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateClient,
		arg.ID,
		arg.ClientName,
		arg.ClientSurname,
		arg.Birthday,
		arg.Gender,
		arg.AddressID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
