// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package sqlc_generated

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAddress = `-- name: AddAddress :exec
INSERT INTO address (id, country,city,street)
VALUES ($1, $2, $3, $4)
`

type AddAddressParams struct {
	ID      uuid.UUID
	Country interface{}
	City    interface{}
	Street  interface{}
}

func (q *Queries) AddAddress(ctx context.Context, arg AddAddressParams) error {
	_, err := q.db.Exec(ctx, addAddress,
		arg.ID,
		arg.Country,
		arg.City,
		arg.Street,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO client (id, client_name,client_surname,birthday,gender,address_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING registration_date
`

type CreateUserParams struct {
	ID            uuid.UUID
	ClientName    interface{}
	ClientSurname interface{}
	Birthday      time.Time
	Gender        GenderT
	AddressID     pgtype.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.ClientName,
		arg.ClientSurname,
		arg.Birthday,
		arg.Gender,
		arg.AddressID,
	)
	var registration_date pgtype.Timestamptz
	err := row.Scan(&registration_date)
	return registration_date, err
}
