// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc_generated

import (
	"context"

	uuid "github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, created_at, token_version
FROM "user"
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at, token_version
FROM "user"
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.TokenVersion,
	)
	return i, err
}

const incrementTokenVersion = `-- name: IncrementTokenVersion :execrows
UPDATE "user"
SET token_version = token_version + 1
WHERE id = $1
`

func (q *Queries) IncrementTokenVersion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incrementTokenVersion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
