name: CI

on:
  pull_request:
    paths:
      - "cmd/**"
      - "internal/**"
      - "infra/db/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/**"
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go: [ '1.24' ]

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: appdb
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # Внутри job’а сервис доступен по имени "postgres"
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/appdb?sslmode=disable

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Install tools (sqlc, migrate)
        run: |
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
          go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest
          # go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Generate SQL code
        run: |
          sqlc generate

      - name: Wait for DB
        run: |
          for i in {1..30}; do
            pg_isready -h postgres -U postgres && break
            sleep 1
          done
      - name: Run DB migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/appdb?sslmode=disable
        run: |
          migrate -path ./internal/infra/db/migrations -database "$DATABASE_URL" up

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v ./...
